CREATE TABLE races (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    distance DOUBLE PRECISION NOT NULL,
    elevation INTEGER NOT NULL,
    location VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    price NUMERIC(19, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    itra INTEGER,
    description TEXT,
    website_url VARCHAR(2048)
);